### ISSUE TITLE
Error Installing: The system cannot find the file specified

### ISSUE THREAD

**Issue by ngtjah** [JMonsorno/Chocolatey-VBoxGuestAdditions#1]
I'm having a bit of trouble installing vboxguestadditions.install on Server 2012 R2.

https://gist.github.com/ngtjah/7fdb21a0870d5cb10435

Thanks

**Comment by JMonsorno** [comment]
Fixed but can't update Chocolatey.
Version 4.3.20 - 4.3.26 now available here: https://www.myget.org/F/jmonsorno-choco/api/v2

Example:

> choco install VBoxGuestAdditions.install -version 4.3.20 -source  https://www.myget.org/F/jmonsorno-choco/api/v2

I've also added 7zip.install lastest version available (9.38) to my feed for the dependency so it will work with a single install command.
